"""
Ca Assay (Calcium Flux) Protocol - Generated by Plate Reader App
=================================================================
Protocol for Fluo-4 AM calcium flux assay.

Workflow:
1. Cell plate pre-wash (2x 150 µL PBS)
2. Dye loading (50 µL Fluo-4 AM solution)
3. Dye loading incubation (60 min @ 37°C)
4. Post-load wash (0x) -> Leave 60 µL buffer for equilibration
5. Equilibration (15 min RT + 15 min @ 37°C)
6. Compound dilution preparation

** COMPOUND ADDITION TO CELLS NOT INCLUDED IN PROTOCOL **
Add compounds manually after equilibration for precise timing control.
Aspirate existing buffer, then add 60 µL compound solution at FINAL concentration.

COMPOUND PREPARATION:
- Compounds are prepared at FINAL concentration (no in-well dilution)
- Treatment volume: 60 µL per well
- Full volume replacement: aspirate existing liquid, then dispense compound

=== REAGENTS TO PREPARE (3 buffers + Fluo-4 stock) ===
Note: post-load washes, equilibration, compound dilution buffer, and the dye-loading base
are ALL the same assay buffer [2] - prepare it once.

[1] PBS (plain, NO probenecid) - for pre-load washes only:
- Total: 30.8 mL

[2] ASSAY BUFFER (with probenecid + Brilliant Black) - prepare ONE batch:
    Used for post-load washes, equilibration, compound dilution buffer, and the dye loading base [3].
- Base buffer (HBSS + HEPES + BSA): 19.3 mL
- ION Biosciences 100x Probenecid: 197 µL
- Brilliant Black (50 mM stock): 196.5 µL -> 500 µM final
- TOTAL to make: 19.7 mL

[3] DYE LOADING SOLUTION (prepare fresh - take 6.71 mL of assay buffer [2], add:)
- Fluo-4 AM (1 mM stock): 20.4 µL -> 3 µM final
- ION Biosciences 100x Pluronic: 68.0 µL
- Total loading solution: 6.8 mL

FLUO-4 AM STOCK PREPARATION (from 50 µg vial):
- Reconstitute 50 µg in 50 µL anhydrous DMSO = ~1 mM stock
- Store at -20°C protected from light
- Use within same day for best results
"""

from opentrons import protocol_api
from opentrons.types import Point
from opentrons.protocol_api import SINGLE, ALL
import json

metadata = {
    "protocolName": "CHO-M5 Carbachol and PAC-3310 calcium flux",
    "author": "Generated by Plate Reader App",
    "description": "Carbachol and PAC-3310 concentration-response protocol for the CHO-M5 calcium-flux assay",
}

requirements = {"robotType": "OT-2", "apiLevel": "2.20"}


def _transfer_in_chunks(pipette, volume_ul, source, dest, chunk_ul=300, aspirate_z=2, dispense_z=2, do_blow_out=True):
    """Aspirate/dispense 'volume_ul' in <=chunk_ul steps."""
    remaining = float(volume_ul)
    while remaining > 0.0001:
        step = chunk_ul if remaining > chunk_ul else remaining
        pipette.aspirate(step, source.bottom(aspirate_z))
        pipette.dispense(step, dest.bottom(dispense_z))
        remaining = round(remaining - step, 4)
    if do_blow_out:
        pipette.blow_out(dest.top())


def run(protocol: protocol_api.ProtocolContext):

    # ================================================
    # Custom labware definitions
    # ================================================

    custom_reservoir_def = json.loads(r"""{
  "ordering": [["A1","B1","C1","D1","E1","F1","G1","H1"]],
  "brand": {"brand": "Custom Reservoir ", "brandId": []},
  "metadata": {
    "displayName": "Custom Reservoir 8 Reservoir 100000 µL",
    "displayCategory": "reservoir",
    "displayVolumeUnits": "µL",
    "tags": []
  },
  "dimensions": {"xDimension": 127.3, "yDimension": 85, "zDimension": 33.7},
  "wells": {
    "A1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 84.9, "z": 8.7},
    "B1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 75.9, "z": 8.7},
    "C1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 66.9, "z": 8.7},
    "D1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 57.9, "z": 8.7},
    "E1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 48.9, "z": 8.7},
    "F1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 39.9, "z": 8.7},
    "G1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 30.9, "z": 8.7},
    "H1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 21.9, "z": 8.7}
  },
  "groups": [{"metadata": {"wellBottomShape": "v"}, "wells": ["A1","B1","C1","D1","E1","F1","G1","H1"]}],
  "parameters": {
    "format": "irregular",
    "quirks": [],
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "customreservoir_8_reservoir_100000ul"
  },
  "namespace": "custom_beta",
  "version": 4,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {"x": 0, "y": 0, "z": 0}
}""")

    # ================================================
    # Labware setup
    # ================================================

    # Tube rack for compound stocks
    tuberack = protocol.load_labware(
        load_name="opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap",
        location="1",
        label="Tube rack (compound stocks)",
    )

    # Buffer reservoir (PBS first, then replaced with assay buffer after pre-load washes)
    buffer_reservoir = protocol.load_labware_from_definition(
        custom_reservoir_def,
        "6",
        "Buffer reservoir (PBS -> Assay buffer)",
    )
    buffer = buffer_reservoir.wells()[0]

    # Dye loading reservoir (separate, to avoid contamination)
    dye_loading_reservoir = protocol.load_labware_from_definition(
        custom_reservoir_def,
        "10",
        "Dye loading solution",
    )

    # Deep well plate for compound dilutions
    dilution_plate = protocol.load_labware(
        load_name="nest_96_wellplate_2ml_deep",
        location="2",
        label="Deep well plate (dilutions)",
    )

    # Cell plate
    cell_plate = protocol.load_labware(
        load_name="corning_96_wellplate_360ul_flat",
        location="3",
        label="Cell plate",
    )

    # Waste wells in dilution plate (columns 9, 10, 11, 12)
    # Using column tops only - 8-channel pipette will dispense to entire column
    waste_wells = [dilution_plate.columns()[8][0], dilution_plate.columns()[9][0], dilution_plate.columns()[10][0], dilution_plate.columns()[11][0]]
    waste_idx = 0

    # Tip racks
    tiprack_20 = protocol.load_labware(
        load_name="opentrons_96_tiprack_20ul",
        location="8",
        label="20 µL tip rack",
    )

    tiprack_300 = protocol.load_labware(
        load_name="opentrons_96_tiprack_300ul",
        location="4",
        label="300 µL tip rack",
    )

    # Reset any persistent offset from previous runs
    tiprack_300.set_offset(x=0, y=0, z=0)
    offset_mm = (3 - 1) * 9.0
    tiprack_300.set_offset(x=offset_mm, y=0, z=0)

    # ================================================
    # Pipette setup
    # ================================================

    # P20 not loaded — P200-only mode (all single-well steps use the P300 in single-tip mode)

    p300 = protocol.load_instrument(
        instrument_name="p300_multi",
        mount="left",
        tip_racks=[tiprack_300],
    )

    # Set P300 to single-tip mode
    p300.configure_nozzle_layout(
        style=protocol_api.SINGLE,
        start="H1",
        tip_racks=[tiprack_300],
    )

    # ================================================
    # Initial Setup
    # ================================================


    protocol.pause("DECK SETUP: Tube rack slot 1 (Carbachol in A1, PAC-3310 in A2, Pure DMSO in D6), cell plate slot 3, deep well slot 2. Buffer reservoir slot 6 (dilution buffer added per mixture group). Have ready: PBS (30.8 mL) for pre-wash.")

    # ================================================
    # PHASE 1: Compound Dilution Preparation (Serial Dilution)
    # ================================================
    # Compounds are prepared at FINAL concentration (no in-well dilution).
    # Treatment volume: 60 µL per well
    # Mixture groups: 1
    # No preincubation compounds
    # Treatment: aspirate existing liquid, dispense treatment compound
    # DMSO normalization: ENABLED (pure DMSO in tube D6)

    protocol.comment("Preparing compound dilutions via serial dilution (1 mixture group(s))")

    # Pure DMSO for normalization (ensures equal DMSO concentration across dilution series)
    dmso = tuberack.wells_by_name()["D6"]

    protocol.pause("DILUTION BUFFER PREP: [1] Ca2+ Default: 10.72 mL HBSS + HEPES + BSA + 109.4 µL Probenecid + 109.4 µL Brilliant Black. Add to reservoir slot 6. >> RESUME")

    # Stock and destination wells for Carbachol
    carbachol_stock = tuberack.wells_by_name()["A1"]
    dest_carbachol_wells = [dilution_plate.wells_by_name()[w] for w in ["A1", "B1", "C1", "D1", "E1", "F1", "G1"]]

    # Stock and destination wells for PAC-3310
    pac_3310_stock = tuberack.wells_by_name()["A2"]
    dest_pac_3310_wells = [dilution_plate.wells_by_name()[w] for w in ["A2", "B2", "C2", "D2", "E2", "F2", "G2"]]

    # ----- Step 1: Pre-fill all wells with assay buffer -----
    protocol.comment("Pre-filling dilution wells with assay buffer")
    p300.pick_up_tip()

    # Control -> H1 (560.0 µL)
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=560.0,
        source=buffer,
        dest=dilution_plate.wells_by_name()["H1"],
        chunk_ul=300,
        aspirate_z=2,
        dispense_z=2,
        do_blow_out=False
    )

    # Control -> H2 (560.0 µL)
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=560.0,
        source=buffer,
        dest=dilution_plate.wells_by_name()["H2"],
        chunk_ul=300,
        aspirate_z=2,
        dispense_z=2,
        do_blow_out=False
    )

    # Pre-fill buffer for Carbachol wells
    protocol.comment("Filling Carbachol buffer wells")
    buffer_volumes_carbachol = [609.8, 560.0, 560.0, 559.9, 559.4, 554.4, 504.0]
    for well, vol in zip(dest_carbachol_wells, buffer_volumes_carbachol):
        if vol > 0:
            _transfer_in_chunks(pipette=p300, volume_ul=vol, source=buffer, dest=well, chunk_ul=300, aspirate_z=2, dispense_z=2, do_blow_out=False)

    # Pre-fill buffer for PAC-3310 wells
    protocol.comment("Filling PAC-3310 buffer wells")
    buffer_volumes_pac_3310 = [616.0, 560.0, 560.0, 559.9, 559.4, 554.4, 504.0]
    for well, vol in zip(dest_pac_3310_wells, buffer_volumes_pac_3310):
        if vol > 0:
            _transfer_in_chunks(pipette=p300, volume_ul=vol, source=buffer, dest=well, chunk_ul=300, aspirate_z=2, dispense_z=2, do_blow_out=False)
    p300.drop_tip()

    # ----- Carbachol Serial Dilution -----
    # Stock: A1, Dilution factor: 1:10.0
    # Wells (high to low): A1 -> B1 -> C1 -> D1 -> E1 -> F1 -> G1
    # TARGET CONCENTRATIONS: A1=10.0µM(-5.0), B1=1.0µM(-6.0), C1=100nM(-7.0), D1=10nM(-8.0), E1=1nM(-9.0), F1=0nM(-10.0), G1=0nM(-11.0)

    protocol.comment("Carbachol serial dilution: A1 -> B1 -> C1 -> D1 -> E1 -> F1 -> G1")

    # Step 2: Add stock to first dilution well (12.44 µL)
    p300.pick_up_tip()

    # Pre-wet for accuracy
    p300.aspirate(12.44, carbachol_stock.bottom(1))
    p300.dispense(12.44, carbachol_stock.bottom(1))

    # Transfer stock to first well
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=12.44,
        source=carbachol_stock,
        dest=dest_carbachol_wells[0],
        chunk_ul=300,
        aspirate_z=1,
        dispense_z=2,
    )
    p300.drop_tip()

    # Step 3: Serial dilutions
    # Transfer volumes: [62.22, 62.22, 62.22, 62.16, 61.60, 56.00] µL

    p300.pick_up_tip()

    for i in range(6):
        src = dest_carbachol_wells[i]
        dst = dest_carbachol_wells[i + 1]
        transfer_vol = [62.22, 62.22, 62.22, 62.16, 61.60, 56.00][i]

        # Skip control wells (0 µL transfers will be handled separately)
        if transfer_vol == 0:
            continue

        # Mix the first well before first transfer
        if i == 0:
            p300.mix(5, 280, src.bottom(2))

        # Transfer and mix
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=transfer_vol,
            source=src,
            dest=dst,
            chunk_ul=300,
            aspirate_z=2,
            dispense_z=2,
            do_blow_out=False,  # Skip blow_out here, do it after mixing
        )
        p300.mix(5, 280, dst.bottom(2))
        p300.blow_out(dst.top())

    p300.drop_tip()

    # ----- PAC-3310 Serial Dilution -----
    # Stock: A2, Dilution factor: 1:10.0
    # Wells (high to low): A2 -> B2 -> C2 -> D2 -> E2 -> F2 -> G2
    # TARGET CONCENTRATIONS: A2=10.0µM(-5.0), B2=1.0µM(-6.0), C2=100nM(-7.0), D2=10nM(-8.0), E2=1nM(-9.0), F2=0nM(-10.0), G2=0nM(-11.0)

    protocol.comment("PAC-3310 serial dilution: A2 -> B2 -> C2 -> D2 -> E2 -> F2 -> G2")

    # Step 2: Add stock to first dilution well (6.22 µL)
    p300.pick_up_tip()

    # Pre-wet for accuracy
    p300.aspirate(6.22, pac_3310_stock.bottom(1))
    p300.dispense(6.22, pac_3310_stock.bottom(1))

    # Transfer stock to first well
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=6.22,
        source=pac_3310_stock,
        dest=dest_pac_3310_wells[0],
        chunk_ul=300,
        aspirate_z=1,
        dispense_z=2,
    )
    p300.drop_tip()

    # Step 2.5: DMSO normalization (6.22 µL to wells 2-7 + 1 control wells)
    # This ensures equal DMSO concentration across all dilution points and controls
    protocol.comment("Normalizing DMSO concentration across dilution series and control wells")

    p300.pick_up_tip()

    # Add 6.22 µL of pure DMSO to wells 2-7
    for well in dest_pac_3310_wells[1:]:
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=6.22,
            source=dmso,
            dest=well,
            chunk_ul=300,
            aspirate_z=1,
            dispense_z=2,
        )

    # Add DMSO to control wells for this compound
    for well_name in ["H2"]:
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=6.22,
            source=dmso,
            dest=dilution_plate.wells_by_name()[well_name],
            chunk_ul=300,
            aspirate_z=1,
            dispense_z=2,
        )

    # Mix control wells (not part of serial dilution, so mix after DMSO addition)
    for well_name in ["H2"]:
        p300.mix(5, 280, dilution_plate.wells_by_name()[well_name].bottom(2))
        p300.blow_out(dilution_plate.wells_by_name()[well_name].top())

    p300.drop_tip()

    # Step 3: Serial dilutions
    # Transfer volumes: [62.22, 62.22, 62.22, 62.16, 61.60, 56.00] µL

    p300.pick_up_tip()

    for i in range(6):
        src = dest_pac_3310_wells[i]
        dst = dest_pac_3310_wells[i + 1]
        transfer_vol = [62.22, 62.22, 62.22, 62.16, 61.60, 56.00][i]

        # Skip control wells (0 µL transfers will be handled separately)
        if transfer_vol == 0:
            continue

        # Mix the first well before first transfer
        if i == 0:
            p300.mix(5, 280, src.bottom(2))

        # Transfer and mix
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=transfer_vol,
            source=src,
            dest=dst,
            chunk_ul=300,
            aspirate_z=2,
            dispense_z=2,
            do_blow_out=False,  # Skip blow_out here, do it after mixing
        )
        p300.mix(5, 280, dst.bottom(2))
        p300.blow_out(dst.top())

    p300.drop_tip()

    protocol.comment("Compound dilution preparation complete")

    # ================================================
    # PHASE 2: Cell Plate Pre-Wash
    # ================================================
    # Remove serum-containing media and wash 2x with PBS
    # (PBS used for pre-load washes - no probenecid needed before dye loading)

    protocol.pause("PRE-WASH & DYE LOADING PREP: (1) Ensure PBS (30.8 mL) is in buffer reservoir (slot 6). (2) Prepare dye loading solution: Add 20.4 µL Fluo-4 AM + 68.0 µL Pluronic to 6.71 mL assay buffer, mix well, add to dye reservoir (slot 10). Resume to start pre-wash.")

    protocol.comment("Starting pre-load wash (2x 150 µL PBS)")

    # Switch to 8-channel mode for cell plate operations
    p300.configure_nozzle_layout(
        style=protocol_api.ALL,
        start="A1",
        tip_racks=[tiprack_300],
    )

    # Save original flow rates
    original_aspirate_rate = p300.flow_rate.aspirate
    original_dispense_rate = p300.flow_rate.dispense

    # Remove existing media from cells
    protocol.comment("Removing existing media from cells")

    p300.pick_up_tip()
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(150, cell_plate.columns()[col_idx][0].bottom(1))
        p300.flow_rate.dispense = 150  # Fast dispense for waste
        p300.dispense(150, waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out()
        p300.blow_out()  # Double blow_out for thorough liquid clearing
        waste_idx += 1

    # Pre-load wash cycle 1 (PBS)
    protocol.comment("Pre-load wash cycle 1 of 2 (PBS)")
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(150, buffer_reservoir.wells()[0].bottom(2))
        p300.flow_rate.dispense = 40  # Slow dispense for cells
        p300.dispense(150, cell_plate.columns()[col_idx][0].bottom(1.5).move(Point(x=1.5, y=0, z=0)))
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(170, cell_plate.columns()[col_idx][0].bottom(1))
        p300.flow_rate.dispense = 150  # Fast dispense for waste
        p300.dispense(170, waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out()
        p300.blow_out()  # Double blow_out for thorough liquid clearing
        waste_idx += 1

    # Pre-load wash cycle 2 (PBS)
    protocol.comment("Pre-load wash cycle 2 of 2 (PBS)")
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(150, buffer_reservoir.wells()[0].bottom(2))
        p300.flow_rate.dispense = 40  # Slow dispense for cells
        p300.dispense(150, cell_plate.columns()[col_idx][0].bottom(1.5).move(Point(x=1.5, y=0, z=0)))
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(170, cell_plate.columns()[col_idx][0].bottom(1))
        p300.flow_rate.dispense = 150  # Fast dispense for waste
        p300.dispense(170, waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out()
        p300.blow_out()  # Double blow_out for thorough liquid clearing
        waste_idx += 1

    # Restore original flow rates
    p300.flow_rate.aspirate = original_aspirate_rate
    p300.flow_rate.dispense = original_dispense_rate
    # Keep tips for dye loading (no drop_tip here)

    # ================================================
    # PHASE 3: Dye Loading
    # ================================================

    protocol.comment("Dispensing dye loading solution to cells")

    # Already in 8-channel mode from pre-load wash, reusing same tips
    p300.flow_rate.dispense = 40  # Slow dispense for cells
    for col_idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
        p300.aspirate(50, dye_loading_reservoir.wells()[0].bottom(2))
        p300.dispense(50, cell_plate.columns()[col_idx][0].bottom(1.5).move(Point(x=1.5, y=0, z=0)))
        p300.blow_out()

    p300.flow_rate.dispense = 150  # Reset dispense rate
    p300.drop_tip()

    protocol.pause("DYE INCUBATION: Cover plate, incubate 60 min at 37C in dark. Protocol complete after incubation - add compounds manually for precise timing control.")

    # ================================================
    # PHASE 4: Protocol Complete
    # ================================================

    protocol.comment("Ca assay protocol complete!")
    protocol.comment("All treatment compound transfers and plate reader measurements completed")

    protocol.pause("PROTOCOL COMPLETE: All transfers and measurements done. Resume to finish.")
