import json
from opentrons import protocol_api
from opentrons.types import Point
from opentrons.protocol_api import SINGLE, ALL

metadata = {
    "protocolName": "CHO-M2 Carbachol cAMP",
    "author": "Generated by Plate Reader App",
    "description": "Carbachol concentration-response protocol for the CHO-M2 cAMP assay",
    "created": "2026-08-14",
}

requirements = {"robotType": "OT-2", "apiLevel": "2.20"}


def _transfer_in_chunks(pipette, volume_ul, source, dest, chunk_ul=300, aspirate_z=2, dispense_z=2, do_blow_out=True):
    """Aspirate/dispense 'volume_ul' in <=chunk_ul steps."""
    remaining = float(volume_ul)
    while remaining > 0.0001:
        step = chunk_ul if remaining > chunk_ul else remaining
        pipette.aspirate(step, source.bottom(aspirate_z))
        pipette.dispense(step, dest.bottom(dispense_z))
        remaining = round(remaining - step, 4)
    if do_blow_out:
        pipette.blow_out(dest.top())


def run(protocol: protocol_api.ProtocolContext):

    # -----------------------------
    # Custom labware definitions
    # -----------------------------

    # Custom 8-well reservoir (100,000 µL per well)
    custom_reservoir_def = json.loads(r"""{
  "ordering": [["A1","B1","C1","D1","E1","F1","G1","H1"]],
  "brand": {"brand": "Custom Reservoir ", "brandId": []},
  "metadata": {
    "displayName": "Custom Reservoir 8 Reservoir 100000 µL",
    "displayCategory": "reservoir",
    "displayVolumeUnits": "µL",
    "tags": []
  },
  "dimensions": {"xDimension": 127.3, "yDimension": 85, "zDimension": 33.7},
  "wells": {
    "A1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 84.9, "z": 8.7},
    "B1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 75.9, "z": 8.7},
    "C1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 66.9, "z": 8.7},
    "D1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 57.9, "z": 8.7},
    "E1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 48.9, "z": 8.7},
    "F1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 39.9, "z": 8.7},
    "G1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 30.9, "z": 8.7},
    "H1": {"depth": 25, "totalLiquidVolume": 100000, "shape": "circular", "diameter": 10, "x": 30, "y": 21.9, "z": 8.7}
  },
  "groups": [{"metadata": {"wellBottomShape": "v"}, "wells": ["A1","B1","C1","D1","E1","F1","G1","H1"]}],
  "parameters": {
    "format": "irregular",
    "quirks": [],
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "customreservoir_8_reservoir_100000ul"
  },
  "namespace": "custom_beta",
  "version": 4,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {"x": 0, "y": 0, "z": 0}
}""")

    # -----------------------------
    # Labware setup
    # -----------------------------

    # Tube rack for compound stocks (stocks in row A)
    tuberack = protocol.load_labware(
        load_name="opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap",
        location="1",
        label="Tube rack (compound stocks in row A)",
    )

    # Custom buffer reservoir (8 wells × 100,000 µL)
    buffer_reservoir = protocol.load_labware_from_definition(
        custom_reservoir_def,
        "6",
        "Buffer reservoir (custom)",
    )

    # Dilution plate (NEST 96 deepwell plate)
    dilution_plate = protocol.load_labware(
        load_name="nest_96_wellplate_2ml_deep",
        location="2",
        label="Dilution plate (NEST 2 mL deepwell)",
    )

    # Tip racks
    tiprack_20 = protocol.load_labware(
        load_name="opentrons_96_tiprack_20ul",
        location="8",
        label="20 µL tip rack",
    )

    tiprack_300 = protocol.load_labware(
        load_name="opentrons_96_tiprack_300ul",
        location="4",
        label="300 µL tip rack",
    )

    # Reset any persistent offset from previous runs, then apply desired offset
    tiprack_300.set_offset(x=0, y=0, z=0)


    # -----------------------------
    # Instruments
    # -----------------------------

    # P300 multi-channel in single-tip mode
    p300 = protocol.load_instrument(
        instrument_name="p300_multi",
        mount="left",
        tip_racks=[tiprack_300],
    )

    # P20 not loaded — P200-only mode (all single-well steps use the P300 in single-tip mode)

    # Configure P300 for single-tip operation
    p300.configure_nozzle_layout(
        style=SINGLE,
        start="H1",
        tip_racks=[tiprack_300],
    )

    # -----------------------------
    # Reagents
    # -----------------------------

    buffer = buffer_reservoir.wells_by_name()["A1"]


    # ===== MIXTURE SET 1: FSK+IBMX =====
    protocol.comment("Preparing dilutions for mixture set: FSK+IBMX")

    protocol.pause("DILUTION BUFFER PREP: [1] FSK+IBMX: 8.82 mL buffer + 5.3 µL Forskolin + 8.8 µL IBMX. Add to reservoir slot 6. STOCK PLACEMENTS in tube rack slot 1: A1: Carbachol. >> RESUME")

    # -----------------------------
    # Carbachol dilution series (0.00001 to 1.00e-11 M)
    # -----------------------------

    protocol.comment("Preparing Carbachol dilution series in column 1")

    # Stock location
    carbachol_stock = tuberack.wells_by_name()["A1"]

    # Destination wells (B1, C1, D1, E1, F1, G1, H1)
    dest_carbachol_wells = [dilution_plate.wells_by_name()[w] for w in ["B1", "C1", "D1", "E1", "F1", "G1", "H1"]]

    # Step 0: Fill well A1 with control buffer (for later transfer to control wells)
    control_buffer_well = dilution_plate.wells_by_name()["A1"]
    protocol.comment("Filling A1 with 850 µL control buffer (8 controls × 100 µL + 50 µL overage)")

    p300.pick_up_tip()
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=850.0,
        source=buffer,
        dest=control_buffer_well,
        chunk_ul=300,
        aspirate_z=2,
        dispense_z=2,
    )
    # Keep tip for next step (buffer pre-fill)

    # Step 1: Pre-fill buffer into dilution wells
    buffer_volumes_carbachol = [925.6, 850.0, 850.0, 849.9, 849.1, 841.5, 765.0]  # µL

    # Reusing tip from control buffer fill
    for well, vol in zip(dest_carbachol_wells, buffer_volumes_carbachol):
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=vol,
            source=buffer,
            dest=well,
            chunk_ul=300,
            aspirate_z=2,
            dispense_z=2,
        )
    p300.drop_tip()

    # Step 2: Add stock to first dilution well (18.89 µL)
    p300.pick_up_tip()

    # Pre-wet for accuracy
    p300.aspirate(18.89, carbachol_stock.bottom(1))
    p300.dispense(18.89, carbachol_stock.bottom(1))

    # Transfer stock to first well
    _transfer_in_chunks(
        pipette=p300,
        volume_ul=18.89,
        source=carbachol_stock,
        dest=dest_carbachol_wells[0],
        chunk_ul=300,
        aspirate_z=1,
        dispense_z=2,
    )
    p300.drop_tip()

    # Step 3: Serial dilutions
    # Transfer volumes: [94.44, 94.44, 94.44, 94.35, 93.50, 85.00] µL

    p300.pick_up_tip()

    for i in range(6):
        src = dest_carbachol_wells[i]
        dst = dest_carbachol_wells[i + 1]
        transfer_vol = [94.44, 94.44, 94.44, 94.35, 93.50, 85.00][i]

        # Skip control wells (0 µL transfers will be handled separately)
        if transfer_vol == 0:
            continue

        # Mix the first well before first transfer
        if i == 0:
            p300.mix(5, 300, src.bottom(2))

        # Transfer and mix
        _transfer_in_chunks(
            pipette=p300,
            volume_ul=transfer_vol,
            source=src,
            dest=dst,
            chunk_ul=300,
            aspirate_z=2,
            dispense_z=2,
            do_blow_out=False,  # Skip blow_out here, do it after mixing
        )
        p300.mix(5, 300, dst.bottom(2))
        p300.blow_out(dst.top())

    p300.drop_tip()

    protocol.comment("Carbachol dilution complete")

    # ===== ALL DILUTIONS COMPLETE =====
    protocol.comment("All dilution preparations complete for 1 mixture set(s)")


    # ===== CHECKPOINT: Running full protocol from beginning =====
    protocol.comment("Running full protocol from beginning")

    # ===== CELL PLATE SETUP =====
    # Load cell plate
    cell_plate = protocol.load_labware('nest_96_wellplate_200ul_flat', 3)

    # Waste wells in dilution plate (entire column 12)
    waste_wells = [dilution_plate.wells_by_name()["A12"], dilution_plate.wells_by_name()["B12"], dilution_plate.wells_by_name()["C12"], dilution_plate.wells_by_name()["D12"], dilution_plate.wells_by_name()["E12"], dilution_plate.wells_by_name()["F12"], dilution_plate.wells_by_name()["G12"], dilution_plate.wells_by_name()["H12"]]
    waste_idx = 0

    # ===== PAUSE FOR CELL PLATE SETUP =====
    protocol.pause("Dilution preparation complete. Please place the 96-well cell plate into slot 3, then click RESUME to continue with cell plate handling.")

    # ===== CELL PLATE HANDLING =====
    protocol.comment("Starting cell plate media exchange and compound addition")

    # Save original dispense rate (will set to 40 µL/s only when dispensing into cells)
    original_dispense_rate = p300.flow_rate.dispense


    # ===== MIXTURE: FSK+IBMX =====

    # Processing Carbachol (randomized batch order)
    protocol.comment("Starting Carbachol treatment")
    p300.pick_up_tip()

    original_dispense_rate = p300.flow_rate.dispense
    batches = [
        {"source": "C1", "wells": ["F6", "H5", "A8"], "label": "Carbachol at 0.000001 M"},
        {"source": "B1", "wells": ["B7", "G9"], "label": "Carbachol at 0.00001 M"},
        {"source": "G1", "wells": ["E9", "B8", "A4"], "label": "Carbachol at 1e-10 M"},
        {"source": "B1", "wells": ["H4", "E4", "C7"], "label": "Carbachol at 0.00001 M"},
        {"source": "F1", "wells": ["H10", "C4", "D3"], "label": "Carbachol at 1e-9 M"},
        {"source": "A1", "wells": ["H6", "B3", "C5"], "label": "Control (buffer from A1)"},
        {"source": "E1", "wells": ["F10", "E8"], "label": "Carbachol at 1e-8 M"},
        {"source": "H1", "wells": ["A6", "H3", "D5"], "label": "Carbachol at 1e-11 M"},
        {"source": "H1", "wells": ["E6", "B6", "D4"], "label": "Carbachol at 1e-11 M"},
        {"source": "G1", "wells": ["F3", "G5"], "label": "Carbachol at 1e-10 M"},
        {"source": "F1", "wells": ["F4", "A9"], "label": "Carbachol at 1e-9 M"},
        {"source": "C1", "wells": ["C3", "A10", "B10"], "label": "Carbachol at 0.000001 M"},
        {"source": "E1", "wells": ["G10", "A7", "E10"], "label": "Carbachol at 1e-8 M"},
        {"source": "H1", "wells": ["D10", "B4"], "label": "Carbachol at 1e-11 M"},
        {"source": "D1", "wells": ["C6", "C9"], "label": "Carbachol at 1e-7 M"},
        {"source": "G1", "wells": ["D6", "D8", "A3"], "label": "Carbachol at 1e-10 M"},
        {"source": "F1", "wells": ["H9", "F5", "C10"], "label": "Carbachol at 1e-9 M"},
        {"source": "B1", "wells": ["F9", "B5", "G4"], "label": "Carbachol at 0.00001 M"},
        {"source": "C1", "wells": ["E3", "G8"], "label": "Carbachol at 0.000001 M"},
        {"source": "A1", "wells": ["E7", "H7"], "label": "Control (buffer from A1)"},
        {"source": "E1", "wells": ["F7", "G6", "E5"], "label": "Carbachol at 1e-8 M"},
        {"source": "D1", "wells": ["C8", "H8", "G3"], "label": "Carbachol at 1e-7 M"},
        {"source": "D1", "wells": ["D9", "A5", "F8"], "label": "Carbachol at 1e-7 M"},
        {"source": "A1", "wells": ["G7", "B9", "D7"], "label": "Control (buffer from A1)"}
    ]
    for batch in batches:
        wells = batch["wells"]
        source = dilution_plate.wells_by_name()[batch["source"]].bottom(1)
        vol = 100
        protocol.comment(f"{batch['label']} ({len(wells)} wells)")
        for w in wells:
            p300.aspirate(100, cell_plate.wells_by_name()[w].bottom(1))
        p300.dispense(100 * len(wells), waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out(waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out(waste_wells[waste_idx % len(waste_wells)].top())
        waste_idx += 1
        p300.aspirate(vol * len(wells), source)
        p300.flow_rate.dispense = 40
        for w in wells:
            p300.dispense(vol, cell_plate.wells_by_name()[w].bottom(z=1.5).move(Point(x=1.5, y=0, z=0)))
        p300.blow_out(cell_plate.wells_by_name()[wells[-1]].top())
        p300.flow_rate.dispense = original_dispense_rate

    p300.drop_tip()
    protocol.comment("Carbachol treatment complete")

    protocol.comment("Cell plate handling complete")

    # ===== INCUBATION & HCL LYSIS STEP =====
    protocol.pause("Incubate cells for 15 minutes. Then add 8400 µL of 0.1 M HCl to the reservoir (slot 6) and click RESUME to continue.")
    protocol.comment("Starting HCl lysis: aspirating buffer and replacing with HCl in 64 wells")

    # Process each well: aspirate buffer -> waste -> add HCl (one at a time to prevent drying)
    # Switch tips between compounds to avoid cross-contamination
    original_dispense_rate = p300.flow_rate.dispense
    waste_idx = 0

    # Start with compound group 1 (64 wells)
    p300.pick_up_tip()

    original_dispense_rate = p300.flow_rate.dispense
    batches = [
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F6", "H5", "A8"], "label": "Concentration 0.000001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["B7", "G9"], "label": "Concentration 0.00001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["E9", "B8", "A4"], "label": "Concentration 1e-10"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["H4", "E4", "C7"], "label": "Concentration 0.00001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["H10", "C4", "D3"], "label": "Concentration 1e-9"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["H6", "B3", "C5"], "label": "Control wells"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F10", "E8"], "label": "Concentration 1e-8"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["A6", "H3", "D5"], "label": "Concentration 1e-11"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["E6", "B6", "D4"], "label": "Concentration 1e-11"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F3", "G5"], "label": "Concentration 1e-10"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F4", "A9"], "label": "Concentration 1e-9"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["C3", "A10", "B10"], "label": "Concentration 0.000001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["G10", "A7", "E10"], "label": "Concentration 1e-8"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["D10", "B4"], "label": "Concentration 1e-11"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["C6", "C9"], "label": "Concentration 1e-7"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["D6", "D8", "A3"], "label": "Concentration 1e-10"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["H9", "F5", "C10"], "label": "Concentration 1e-9"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F9", "B5", "G4"], "label": "Concentration 0.00001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["E3", "G8"], "label": "Concentration 0.000001"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["E7", "H7"], "label": "Control wells"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["F7", "G6", "E5"], "label": "Concentration 1e-8"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["C8", "H8", "G3"], "label": "Concentration 1e-7"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["D9", "A5", "F8"], "label": "Concentration 1e-7"},
        {"source": "buffer_reservoir.wells()[0]", "wells": ["G7", "B9", "D7"], "label": "Control wells"}
    ]
    for batch in batches:
        wells = batch["wells"]
        source = buffer_reservoir.wells()[0].bottom(1)
        vol = 100
        protocol.comment(f"{batch['label']} ({len(wells)} wells)")
        for w in wells:
            p300.aspirate(100, cell_plate.wells_by_name()[w].bottom(1))
        p300.dispense(100 * len(wells), waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out(waste_wells[waste_idx % len(waste_wells)].top())
        p300.blow_out(waste_wells[waste_idx % len(waste_wells)].top())
        waste_idx += 1
        p300.aspirate(vol * len(wells), source)
        p300.flow_rate.dispense = 40
        for w in wells:
            p300.dispense(vol, cell_plate.wells_by_name()[w].bottom(z=1.5).move(Point(x=1.5, y=0, z=0)))
        p300.blow_out(cell_plate.wells_by_name()[wells[-1]].top())
        p300.flow_rate.dispense = original_dispense_rate

    p300.drop_tip()

    protocol.comment("HCl lysis complete - cells lysed in 64 wells")

    # Lysis incubation period
    protocol.comment("Lysis incubation: 20 minutes")

    protocol.pause("Wait for 20 minutes of lysis incubation. Then replace the HCl in reservoir (slot 6) with 7120 µL of ELISA buffer before clicking RESUME.")

    # ===== LYSATE DILUTION STEP (DILUTED ONLY) =====
    protocol.comment("Starting lysate dilution: 64 samples (diluted 1:5 only)")
    protocol.comment("Diluted samples: columns 3-10")
    protocol.comment("Undiluted lysate remains in cell plate")

    # Sample -> Deep well plate mapping:
    # Cell plate B3 -> Diluted: A3
    # Cell plate B9 -> Diluted: B3
    # Cell plate C5 -> Diluted: C3
    # Cell plate D7 -> Diluted: D3
    # Cell plate E7 -> Diluted: E3
    # Cell plate G7 -> Diluted: F3
    # Cell plate H6 -> Diluted: G3
    # Cell plate H7 -> Diluted: H3
    # Cell plate B5 -> Diluted: A4
    # Cell plate B7 -> Diluted: B4
    # Cell plate C7 -> Diluted: C4
    # Cell plate E4 -> Diluted: D4
    # Cell plate F9 -> Diluted: E4
    # Cell plate G4 -> Diluted: F4
    # Cell plate G9 -> Diluted: G4
    # Cell plate H4 -> Diluted: H4
    # Cell plate A8 -> Diluted: A5
    # Cell plate A10 -> Diluted: B5
    # Cell plate B10 -> Diluted: C5
    # Cell plate C3 -> Diluted: D5
    # Cell plate E3 -> Diluted: E5
    # Cell plate F6 -> Diluted: F5
    # Cell plate G8 -> Diluted: G5
    # Cell plate H5 -> Diluted: H5
    # Cell plate A5 -> Diluted: A6
    # Cell plate C6 -> Diluted: B6
    # Cell plate C8 -> Diluted: C6
    # Cell plate C9 -> Diluted: D6
    # Cell plate D9 -> Diluted: E6
    # Cell plate F8 -> Diluted: F6
    # Cell plate G3 -> Diluted: G6
    # Cell plate H8 -> Diluted: H6
    # Cell plate A7 -> Diluted: A7
    # Cell plate E5 -> Diluted: B7
    # Cell plate E8 -> Diluted: C7
    # Cell plate E10 -> Diluted: D7
    # Cell plate F7 -> Diluted: E7
    # Cell plate F10 -> Diluted: F7
    # Cell plate G6 -> Diluted: G7
    # Cell plate G10 -> Diluted: H7
    # Cell plate A9 -> Diluted: A8
    # Cell plate C4 -> Diluted: B8
    # Cell plate C10 -> Diluted: C8
    # Cell plate D3 -> Diluted: D8
    # Cell plate F4 -> Diluted: E8
    # Cell plate F5 -> Diluted: F8
    # Cell plate H9 -> Diluted: G8
    # Cell plate H10 -> Diluted: H8
    # Cell plate A3 -> Diluted: A9
    # Cell plate A4 -> Diluted: B9
    # Cell plate B8 -> Diluted: C9
    # Cell plate D6 -> Diluted: D9
    # Cell plate D8 -> Diluted: E9
    # Cell plate E9 -> Diluted: F9
    # Cell plate F3 -> Diluted: G9
    # Cell plate G5 -> Diluted: H9
    # Cell plate A6 -> Diluted: A10
    # Cell plate B4 -> Diluted: B10
    # Cell plate B6 -> Diluted: C10
    # Cell plate D4 -> Diluted: D10
    # Cell plate D5 -> Diluted: E10
    # Cell plate D10 -> Diluted: F10
    # Cell plate E6 -> Diluted: G10
    # Cell plate H3 -> Diluted: H10

    # Step 1: Transfer diluted samples only (mix, aspirate 20 µL)
    p300.pick_up_tip()


    transfers = [("B3", "A3"), ("B9", "B3"), ("C5", "C3"), ("D7", "D3"), ("E7", "E3"), ("G7", "F3"), ("H6", "G3"), ("H7", "H3"), ("B5", "A4"), ("B7", "B4"), ("C7", "C4"), ("E4", "D4"), ("F9", "E4"), ("G4", "F4"), ("G9", "G4"), ("H4", "H4"), ("A8", "A5"), ("A10", "B5"), ("B10", "C5"), ("C3", "D5"), ("E3", "E5"), ("F6", "F5"), ("G8", "G5"), ("H5", "H5"), ("A5", "A6"), ("C6", "B6"), ("C8", "C6"), ("C9", "D6"), ("D9", "E6"), ("F8", "F6"), ("G3", "G6"), ("H8", "H6"), ("A7", "A7"), ("E5", "B7"), ("E8", "C7"), ("E10", "D7"), ("F7", "E7"), ("F10", "F7"), ("G6", "G7"), ("G10", "H7"), ("A9", "A8"), ("C4", "B8"), ("C10", "C8"), ("D3", "D8"), ("F4", "E8"), ("F5", "F8"), ("H9", "G8"), ("H10", "H8"), ("A3", "A9"), ("A4", "B9"), ("B8", "C9"), ("D6", "D9"), ("D8", "E9"), ("E9", "F9"), ("F3", "G9"), ("G5", "H9"), ("A6", "A10"), ("B4", "B10"), ("B6", "C10"), ("D4", "D10"), ("D5", "E10"), ("D10", "F10"), ("E6", "G10"), ("H3", "H10")]
    for src, dst in transfers:
        p300.mix(3, 80, cell_plate.wells_by_name()[src].bottom(1))
        p300.aspirate(20, cell_plate.wells_by_name()[src].bottom(1))
        p300.dispense(20, dilution_plate.wells_by_name()[dst].bottom(2))
        p300.blow_out(dilution_plate.wells_by_name()[dst].top())
    p300.drop_tip()

    # Step 2: Add buffer to all diluted wells (80 µL to make 1:5 dilution)
    # Switch to 8-channel ALL mode for faster buffer addition
    p300.configure_nozzle_layout(style=ALL, start="A1", tip_racks=[tiprack_300])
    p300.pick_up_tip()


    for col in [3, 4, 5, 6, 7, 8, 9, 10]:
        p300.aspirate(80, buffer_reservoir.wells()[0].bottom(1))
        p300.dispense(80, dilution_plate.wells_by_name()[f"A{col}"].bottom(2))
        p300.blow_out(dilution_plate.wells_by_name()[f"A{col}"].top())
    p300.drop_tip()

    # Switch back to single-channel mode
    p300.configure_nozzle_layout(style=SINGLE, start="H1", tip_racks=[tiprack_300])

    protocol.comment("Lysate dilution complete: 64 samples processed (diluted only)")

    # ===== ELISA STANDARDS PREPARATION =====
    protocol.pause("Please place master ELISA standard in tube rack slot A1, and add 7250 µL of ELISA buffer to reservoir (slot 6), then click RESUME to continue.")
    protocol.comment("Preparing 8 ELISA standards via 1:3 serial dilution in deep well plate column 11")

    # Pre-fill all standard wells with 600 µL buffer using 8-channel ALL mode (2x 300 µL)
    p300.configure_nozzle_layout(style=ALL, start="A1", tip_racks=[tiprack_300])
    p300.pick_up_tip()

    # Add 600 µL in two 300 µL transfers
    p300.aspirate(300, buffer_reservoir.wells()[0].bottom(1))
    p300.dispense(300, dilution_plate.wells_by_name()["A11"].bottom(2))
    p300.blow_out(dilution_plate.wells_by_name()["A11"].top())

    p300.aspirate(300, buffer_reservoir.wells()[0].bottom(1))
    p300.dispense(300, dilution_plate.wells_by_name()["A11"].bottom(2))
    p300.blow_out(dilution_plate.wells_by_name()["A11"].top())

    p300.drop_tip()

    # Switch to single-channel mode to add remaining 300 µL to first well only
    p300.configure_nozzle_layout(style=SINGLE, start="H1", tip_racks=[tiprack_300])
    p300.pick_up_tip()

    # Add 300 µL to first well to reach 900 µL total
    p300.aspirate(300, buffer_reservoir.wells()[0].bottom(1))
    p300.dispense(300, dilution_plate.wells_by_name()["A11"].bottom(2))
    p300.blow_out(dilution_plate.wells_by_name()["A11"].top())

    p300.drop_tip()

    # Serial dilution: Add master standard and perform 1:3 dilutions
    p300.pick_up_tip()

    # Add 100 µL master standard to first well
    p300.aspirate(100, tuberack.wells_by_name()["A1"].bottom(2))
    p300.dispense(100, dilution_plate.wells_by_name()["A11"].bottom(2))
    p300.mix(3, 300, dilution_plate.wells_by_name()["A11"].bottom(2))
    p300.blow_out(dilution_plate.wells_by_name()["A11"].top())


    std_wells = ["A11", "B11", "C11", "D11", "E11", "F11", "G11", "H11"]
    for i in range(len(std_wells) - 1):
        p300.aspirate(300, dilution_plate.wells_by_name()[std_wells[i]].bottom(2))
        p300.dispense(300, dilution_plate.wells_by_name()[std_wells[i+1]].bottom(2))
        p300.mix(3, 300, dilution_plate.wells_by_name()[std_wells[i+1]].bottom(2))
        p300.blow_out(dilution_plate.wells_by_name()[std_wells[i+1]].top())
    p300.drop_tip()

    protocol.comment("ELISA standards preparation complete - 8 standards created via 1:3 dilution")

    # ===== ELISA PLATE SETUP =====
    # Load ELISA plate
    elisa_plate = protocol.load_labware('nest_96_wellplate_200ul_flat', 7)

    protocol.pause("Please place ELISA plate in slot 7, then click RESUME to continue.")
    protocol.comment("Setting up ELISA plate: standards in column 1, samples in remaining columns")

    # Prepare standards column (single-channel mode)
    # Use one tip for all buffer additions and standard transfers
    p300.pick_up_tip()

    # A1: 100 µL buffer (blank)
    p300.aspirate(100, buffer_reservoir.wells()[7].bottom(1))
    p300.dispense(100, elisa_plate.wells_by_name()["A1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["A1"].top())

    # B1: 50 µL buffer
    p300.aspirate(50, buffer_reservoir.wells()[7].bottom(1))
    p300.dispense(50, elisa_plate.wells_by_name()["B1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["B1"].top())

    # C1-H1: Transfer 50 µL from diluted standards (reverse order: 7→6→5→4→3→2)
    # Standard 7 (2nd most diluted) → C1, Standard 6 → D1, ..., Standard 2 → H1
    p300.aspirate(50, dilution_plate.wells_by_name()["G11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["C1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["C1"].top())

    p300.aspirate(50, dilution_plate.wells_by_name()["F11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["D1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["D1"].top())

    p300.aspirate(50, dilution_plate.wells_by_name()["E11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["E1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["E1"].top())

    p300.aspirate(50, dilution_plate.wells_by_name()["D11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["F1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["F1"].top())

    p300.aspirate(50, dilution_plate.wells_by_name()["C11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["G1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["G1"].top())

    p300.aspirate(50, dilution_plate.wells_by_name()["B11"].bottom(2))
    p300.dispense(50, elisa_plate.wells_by_name()["H1"].bottom(2))
    p300.blow_out(elisa_plate.wells_by_name()["H1"].top())

    p300.drop_tip()

    protocol.comment("Standards column complete")

    # Switch to 8-channel ALL mode for sample transfer
    p300.configure_nozzle_layout(style=ALL, start="A1", tip_racks=[tiprack_300])

    # Transfer samples from diluted lysate block to ELISA plate (50 µL per well)
    # ELISA plate columns 2+ (offset by 1 due to standards in column 1)
    # Use same tips for all sample columns
    p300.pick_up_tip()

    for src_col, dst_col in [(3, 2), (4, 3), (5, 4), (6, 5), (7, 6), (8, 7), (9, 8), (10, 9)]:
        p300.mix(3, 50, dilution_plate.wells_by_name()[f"A{src_col}"].bottom(2))
        p300.aspirate(50, dilution_plate.wells_by_name()[f"A{src_col}"].bottom(2))
        p300.dispense(50, elisa_plate.wells_by_name()[f"A{dst_col}"].bottom(2))
        p300.blow_out(elisa_plate.wells_by_name()[f"A{dst_col}"].top())
    p300.drop_tip()

    protocol.comment("Sample transfer to ELISA plate complete")

    # ===== ELISA REAGENTS ADDITION =====
    # Load tracer and antiserum reservoirs (custom 8-well format)
    tracer_reservoir = protocol.load_labware_from_definition(custom_reservoir_def, 10, "ELISA tracer reservoir")
    antiserum_reservoir = protocol.load_labware_from_definition(custom_reservoir_def, 11, "ELISA antiserum reservoir")

    protocol.pause("Please add 5600 µL of ELISA tracer to reservoir (slot 10) and 5550 µL of ELISA antiserum to reservoir (slot 11), then click RESUME to continue.")

    protocol.comment("Adding ELISA tracer and antiserum to all wells")

    # Add tracer to ALL wells (standards + samples) - 50 µL per well, using 8-channel
    # Pick up fresh tips for tracer addition
    p300.pick_up_tip()

    for col in [1, 2, 3, 4, 5, 6, 7, 8, 9]:
        p300.aspirate(50, tracer_reservoir.wells()[0].bottom(1))
        p300.dispense(50, elisa_plate.wells_by_name()[f"A{col}"].bottom(2))
        p300.blow_out(elisa_plate.wells_by_name()[f"A{col}"].top())
    p300.drop_tip()

    protocol.comment("Tracer addition complete")

    # Add antiserum to sample wells only (columns 2+) - 50 µL per well, using 8-channel
    # Pick up fresh tips for antiserum addition
    p300.pick_up_tip()

    for col in [2, 3, 4, 5, 6, 7, 8, 9]:
        p300.aspirate(50, antiserum_reservoir.wells()[0].bottom(1))
        p300.dispense(50, elisa_plate.wells_by_name()[f"A{col}"].bottom(2))
        p300.blow_out(elisa_plate.wells_by_name()[f"A{col}"].top())
    p300.drop_tip()

    protocol.comment("Antiserum addition to samples complete")

    # Add antiserum to standards (B1-H1 only, skip A1)
    # Switch back to single-channel mode
    p300.configure_nozzle_layout(style=SINGLE, start="H1", tip_racks=[tiprack_300])

    # Use single tip for all standard wells
    p300.pick_up_tip()

    for row in ["B", "C", "D", "E", "F", "G", "H"]:
        p300.aspirate(50, antiserum_reservoir.wells()[7].bottom(1))
        p300.dispense(50, elisa_plate.wells_by_name()[f"{row}1"].bottom(2))
        p300.blow_out(elisa_plate.wells_by_name()[f"{row}1"].top())

    p300.drop_tip()

    protocol.comment("Antiserum addition to standards complete")
    protocol.comment("ELISA plate preparation complete - ready for incubation")

    protocol.comment("Protocol complete!")
